Django_Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('comments.urls')),
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('links/', views.links, name='links'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('tag/<int:id>/', views.tag_detail, name='tag'),
    path('article/<int:id>/', views.article_detail, name='article'),
    path('category/<slug>/', views.category_detail, name='category'),
    path('search/', views.search, name='search'),
    path('error/<errmsg>/', views.error, name='error'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'

urlpatterns = [
    path('comment/article/<int:article_id>', views.post_comment, name='post_comment'),
]

comments/models.py
from django.db import models


class Comments(models.Model):
    name = models.CharField(max_length=30, verbose_name='昵称')
    email = models.EmailField(max_length=50, verbose_name='邮箱地址')
    url = models.URLField(max_length=50, blank=True, null=True, verbose_name='网址')
    content = models.TextField(verbose_name='评论内容')
    date_publish = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')

    article = models.ForeignKey('blog.article', related_name='comments', on_delete=models.CASCADE)
    p_id = models.ForeignKey('self', related_name='c_id', blank=True, null=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'blog_comments'
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.id)

comments/forms.py
from django import forms
from .models import Comments


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ['name', 'email', 'url', 'content']

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article
from .forms import CommentForm


def post_comment(request, article_id):
    post = get_object_or_404(Article, id=article_id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = post
            comment.save()
            return redirect('blog:article', id=article_id)
    return redirect('blog:article', id=article_id)

templates/article.html
{% extends "base.html" %}
{% load static comments_tags blog_tags%}

{% block title %}{{ article.title }} - {{ SITE_TITLE }}{% endblock %}
{% block description %}{{ article.description }}{% endblock %}
{% block keywords %}{{ SITE_KEYWORDS }}{% endblock %}
{% block itemprop %}{{ article.thumb }}{% endblock %}



{% block breadcrumb %}{% endblock %}
{% block article %}
<link rel="stylesheet" href="{% static "css/github.css" %}">
<article class="blog-post markdown-body">
    <header>
       
        <div class="lead-image">
            <img src="{{ article.thumb }}" alt="" class="img-responsive">
        </div>
    </header>
    <div class="body">
        <h1>{{ article.title }}</h1>
        <div class="meta">
            <i class="fa fa-user"></i> {{ article.author }} 
            <i class="fa fa-calendar"></i>{{ article.date_publish }}
            <i class="fa fa-comments"></i><span class="data"><a href="#comments">{% get_comment_count article %}</a></span>
        </div>
        {{ article.body|safe }}
    </div>
</article>
<aside class="social-icons clearfix">
    <h3>Share on </h3> 
    <a href="#"><i class="fa fa-qq"></i></a>
    <a href="#"><i class="fa fa-weibo"></i></a> 
    <a href="#"><i class="fa fa-wechat"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
</aside>
<aside class="comments" id="comments">
<hr>
<h2><i class="fa fa-comments"></i> {% get_comment_count article %} Comments</h2>
{% include "comments.html" %}
{% include "comment_form.html" %}

{% endblock %}
{% block before_sidebar %}
<!-- widget-toc start -->
<div class="aside-widget widget-toc">
    <header>
        <h3>文章目录</h3>
    </header>

        {{ article.toc|safe }}

</div>
<!-- widget-toc end -->
{% endblock %}

templates/base.html
{% load static %}
{% load bootstrap3 %}
{% load blog_tags %}
{% load blog_tags comments_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width">

    <!-- Font-Awesome -->
    <link rel="stylesheet" href="{% static "css/font-awesome/css/font-awesome.min.css" %}">

    <!-- Styles -->
    <link rel="stylesheet" href="{% static "css/style.css" %}" id="theme-styles">

    <!--[if lt IE 9]>      
        <script src="js/vendor/google/html5-3.6-respond-1.1.0.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="{{ SITE_FAVICON }}" type="image/vnd.microsoft.icon">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta itemprop="image" content="{% block itemprop %}{% endblock %}">
    <!-- CSS -->
    {% bootstrap_css %}
	<!-- JS -->
    {% bootstrap_javascript jquery=1 %}
</head>

<body>
    <header>
        <div class="widewrapper masthead">
            <div class="container">
                <a href="{% url 'blog:index' %}" id="logo">
                    <img src="{% static "img/logo.png" %}" alt="{{ SITE_TITLE }}">
                </a>

                <div id="mobile-nav-toggle" class="pull-right">
                    <a href="#" data-toggle="collapse" data-target=".clean-nav .navbar-collapse">
                        <i class="fa fa-bars"></i>
                    </a>
                </div>

                <nav class="pull-right clean-nav">
                    <div class="collapse navbar-collapse">
                        <ul class="nav nav-pills navbar-nav">
                          
                            <li>
                                <a href="{% url 'blog:index' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:about' %}">About</a>
                            </li>
                            <li>
                                <a href="{% url 'blog:contact' %}">Contact</a>
                            </li>                        
                        </ul>
                    </div>
                </nav>        

            </div>
        </div>

        <div class="widewrapper subheader">
            <div class="container">
                <div class="clean-breadcrumb hidden-xs">
                    <a href="{% url 'blog:index' %}">小文博客</a>
                    {% block breadcrumb %}{% endblock %}
                </div>

                <div class="clean-searchbox">
                    <form action="{% url 'blog:search' %}" method="get" accept-charset="utf-8">
                        <input class="searchfield" name="keyword" id="searchbox" type="text" placeholder="Search">
                        <button class="searchbutton" type="submit">
                            <i class="fa fa-search"></i>
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="widewrapper main">
        <div class="container">
            <div class="row">
                <div class="col-md-8 blog-main">
					<!--  article_list start -->
					{% block article_list %}{% endblock %}
					<!--  article_list end -->
                    {% block article %}{% endblock %}
				</div>
				
                <aside class="col-md-4 blog-aside">
                    <!--  sidebar start -->
                    {% block before_sidebar %}{% endblock %}
					{% include "sidebar.html" %}
                    {% block after_sidebar %}{% endblock %}
					<!--  sidebar end -->
                </aside>
            </div>
        </div>
    </div>

    <footer>
        <!--  footer start -->
		{% include "footer.html" %}
        <!--  footer start -->
    </footer>
    <!-- JS -->

</body>
</html>

templates/category.html
{% extends "base.html" %}


{% block title %}{{ SITE_TITLE }} - {{ SITE_SUBTITLE }}{% endblock %}
{% block description %}{{ category_description }}{% endblock %}
{% block keywords %}{{ SITE_KEYWORDS }}{% endblock %}
{% block itemprop %}{{ SITE_LOGO }}{% endblock %}

{% block breadcrumb %}
: 标签 “{{category_name}}” 下共有 {{article_count}} 篇文章
{% endblock %}
{% block article_list %}
{% if article_count is 0 %}
    <p>该标签下没有文章。</p>
{% endif %}
{% load blog_tags comments_tags %}
{% paginate article_list 4 %}
{% for article in article_list %}
<article class=" blog-teaser">
<header>
    <img src="{{ article.thumb }}" alt="{{ article.title }}">
    <h3><a href="{% url 'blog:article' id=article.id %}">{{ article.title }}</a></h3>
    <span class="meta">{{ article.date_publish }}, {{ article.author }}</span>
    <hr>
</header>
<div class="body">
    {{ article.description }}
</div>
<div class="clearfix">
    <a href="{% url 'blog:article' id=article.id %}" class="btn btn-clean-one">Read more</a>
</div>
</article>
{% endfor %}
{% include "pagination.html" %}
{% endblock %}

templates/comment_form.html
<aside class="create-comment" id="create-comment">
    <hr>
    <h2><i class="fa fa-pencil"></i> Add Comment</h2>
    <form action="{% url 'comments:post_comment' article.id %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <input type="text" name="name" id="comment-name" placeholder="Your Name" class="form-control input-lg">    
            </div>
            <div class="col-md-6">
                <input type="email" name="email" id="comment-email" placeholder="Email" class="form-control input-lg">    
            </div>
        </div>

        <input type="url" name="url" id="comment-url" placeholder="Website" class="form-control input-lg">

        <textarea rows="10" name="content" id="comment-body" placeholder="Your Message" class="form-control input-lg"></textarea>

        <div class="buttons clearfix">
            <button type="submit" class="btn btn-xlarge btn-clean-one">Submit</button>
        </div>
    </form>
</aside>

templates/footer.html
<div class="widewrapper footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-user"></i>关于</h3>

                       <p>本站建立于2018/8/17（七夕），是基于Django建立的个人博客</p>
                       <p></p>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-pencil"></i>所用技术</h3>
                        <ul class="clean-list">
                            <li><a href="">前端技术：bootstrap；</a></li>
                            <li><a href="">后台技术：Django；</a></li>
                            <li><a href="">数据库：Mysql；</a></li>
                            <li><a href="">服务器配置：浪潮云（1C1H1M）；</a></li>
                            <li><a href="">服务器：Nginx+Gunicorn+Django+Python3；</a></li>
                        </ul>
                    </div>

                    <div class="col-md-4 footer-widget">
                        <h3> <i class="fa fa-envelope"></i>联系我们</h3>

                        <p>第一次使用Django开发项目，也是第一个Django上线的项目，希望里面的文章能够帮到大家！</p>
                        <p>如果你有任何疑问可以在文章下面评论，必要时可以点击下面的小图标联系我们！</p>
                         <div class="footer-widget-icon">
                            <i class="fa fa-qq"></i><i class="fa fa-wechat"></i><i class="fa fa-twitter"></i>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>

templates/index.html
{% extends "base.html" %}


{% block title %}
{{ SITE_TITLE }} - {{ SITE_SUBTITLE }}
{% endblock %}
{% block description %}{{ SITE_DESCRIPTION }}{% endblock %}
{% block keywords %}{{ SITE_KEYWORDS }}{% endblock %}
{% block itemprop %}{{ SITE_LOGO }}{% endblock %}


{% block article_list %}
{% include "article_list.html" %}
{% endblock %}

templates/pagination.html
<div id="pagenav" class="noselect">
    <div class="pagenav_btn">
            {% if article_list.has_previous %}
            <div class="previous pull-left">
                <a class="previous-page" href="?page={{ article_list.previous_page_number }}">
                    <button type="button" class="btn btn-default">上一页</button>
                </a>
            </div>
            {% endif %}

        {% if article_list.has_next %}
            <div class="next pull-right">
                <a class="next-page" href="?page={{ article_list.next_page_number }}">
                    <button type="button" class="btn btn-default">下一页</button>
                </a>
            </div>
        {% endif %}
    </div>
</div>

templates/sb_article.html
{% load blog_tags %}
<!-- widget-article start -->
<div class="aside-widget widget-article">
	<header>
		<h3>热门文章</h3>
	</header>
	<div class="body">
		<ul class="clean-list">
        {% get_article_list 'views' 3 as article_hot %}
        {% for article in article_hot %}
            <li><a href=" {% url 'blog:article' id=article.id %}" title="{{ article.title }}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
	</div>
</div>
<div class="aside-widget">
	<header>
		<h3>最受欢迎文章</h3>
	</header>
	<div class="body">
		<ul class="clean-list">
        {% get_article_list 'views' 3 as article_like %}
        {% for article in article_like %}
            <li><a href=" {% url 'blog:article' id=article.id %}" title="{{ article.title }}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
	</div>
</div>
<!-- widget-article end -->

templates/sb_category.html
{% load blog_tags %}
<!-- widget-category start -->
<div class="aside-widget widget-category">
<header>
	<h3>文章分类</h3>
</header>
<div class="body">
	<ul class="clean-list">
        {% get_category_list as category_list %}
        {% for category in category_list %}
            <li><a href=" {% url 'blog:category' slug=category.slug %}" title="{{ category.name }}">{{ category.name }}</a></li>
        {% endfor %}
    </ul>
</div>
</div>
<!-- widget-category end -->

templates/sb_comment.html
{% load comments_tags %}
<!-- widget-comment start -->
<div class="aside-widget widget-comment">
	<header>
		<h3>最新评论</h3>
	</header>
	<div class="body">
		<ul class="clean-list">
			{% get_comment_list as comment_list %}
			{% for comment in comment_list %}
				<li><a href=" {% url 'blog:article' id=comment.article.id %}#comments" title="{{ comment.title }}">{{ comment.content }}</a></li>
			{% endfor %}
		</ul>
	</div>
</div>
<!-- widget-comment end -->

templates/sb_search.html
{% extends "sidebar_base.html" %}
{% block title %}搜索{% endblock %}
{% block body %}{% endblock %}

templates/sb_tag.html
{% load blog_tags %}
<!-- widget-tag start-->
<div class="aside-widget widget-tag">
	<header>
		<h3>标签云</h3>
	</header>
	<div class="body clearfix">
		<ul class="tags">
			{% get_tag_list as tag_list%}
			{% for tag in tag_list %}
				<li><a href=" {% url 'blog:tag' id=tag.id %}" title="{{ tag.name }}">{{ tag.name }}</a></li>
			{% endfor %}                   
		</ul>
	</div>
</div>
<!-- widget-tag end-->

templates/search.html
{% extends "base.html" %}


{% block title %}
{{ SITE_TITLE }} - {{ SITE_SUBTITLE }}
{% endblock %}
{% block description %}{{ SITE_DESCRIPTION }}{% endblock %}
{% block keywords %}{{ SITE_KEYWORDS }}{% endblock %}
{% block itemprop %}{{ SITE_LOGO }}{% endblock %}
{% block breadcrumb %}

: 找到 “{{keyword}}” 相关内容 {{article_count}} 个    


{% endblock %}
{% block article_list %}
{% if article_count is 0 %}
    <p>对不起，没有找到匹配结果。</p>
{% endif %}
{% load blog_tags comments_tags %}
{% paginate article_list 4 %}
{% for article in article_list %}
<article class=" blog-teaser">
<header>
    <img src="{{ article.thumb }}" alt="{{ article.title }}">
    <h3><a href="{% url 'blog:article' id=article.id %}">{{ article.title }}</a></h3>
    <span class="meta">{{ article.date_publish }}, {{ article.author }}</span>
    <hr>
</header>
<div class="body">
    {{ article.description }}
</div>
<div class="clearfix">
    <a href="{% url 'blog:article' id=article.id %}" class="btn btn-clean-one">Read more</a>
</div>
</article>
{% endfor %}
{% include "pagination.html" %}
{% endblock %}

templates/widget.html
{% load staticfiles %}
<link rel="stylesheet" href="{%static "/css/bootstrap/3.3.7/bootstrap.min.css" %}">  

<div class="markdownx row">
    <div class="col-md-6">
        {{ markdownx_editor }}
    </div>
    <div class="col-md-6">
        <div class="markdownx-preview"></div>
    </div>
</div>